# version: '3.8' # Obsolete, can be removed

services:
  backend:
    build: ./gen-ai-backend
    restart: unless-stopped
    env_file:
      - ./gen-ai-backend/.env
    ports: #
      - "8000:8000" # Expose backend port
    depends_on:
      - chromadb
    logging: # <-- ADD THIS BLOCK
      driver: awslogs
      options:
        awslogs-region: ap-south-1 # <-- Your AWS region
        awslogs-group: /ecs/gen-ai-app-backend # <-- Log group name
        awslogs-create-group: "true" # Creates group if it doesn't exist
        

  chromadb:
    image: chromadb/chroma
    restart: unless-stopped
    ports:
      - "8001:8000" # For direct access if needed
    volumes:
      - ./chroma_data:/chroma/.chroma/index

    logging: # <-- ADD THIS BLOCK
      driver: awslogs
      options:
        awslogs-region: ap-south-1 # <-- Your AWS region
        awslogs-group: /ecs/gen-ai-app-chromadb # <-- Log group name
        awslogs-create-group: "true"
        