# version: '3.8' # Obsolete, can be removed

services:
  backend:
    build: ./gen-ai-backend
    restart: unless-stopped
    env_file:
      - ./gen-ai-backend/.env
    depends_on:
      - chromadb

  chromadb:
    image: chromadb/chroma
    restart: unless-stopped
    ports:
      - "8001:8000" # For direct access if needed
    volumes:
      - ./chroma_data:/chroma/.chroma/index